### PR TITLE
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA

### PR DESCRIPTION
**Pull request by errantepiphany**
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA
https://issues.jboss.org/browse/GUVNOR-3023

### CODE REVIEW

**Comment by porcelli** [comment]
@errantepiphany btw.. need fix some conflicts

**Comment by porcelli** [comment]
@wmedvede are you ok with this PR?

**Comment by wmedvede** [comment]
@porcelli @errantepiphany 
I come with some delay to the jackson library mail discussion due to time/zone difference. But I agree the shade is the best option at the point we are right now. I read Davids email this morning and the good news is that the shade worked both for Wildfly 10.0.0 (which aligns with EAP 7.0) and Wildfly 10.1.0.
If the PR can be updated with the shade it'll be great.
Thanks!

**Comment by errantepiphany** [comment]
@porcelli @wmedvede PRs have been updated with the shade fix, as well as rebased and conflicts resolved. Yes, the s2i PR is coming up after these. :)

**Comment by errantepiphany** [comment]
PRs rebased against master. All these go together:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/489
https://github.com/kiegroup/guvnor/pull/485
https://github.com/kiegroup/jbpm-wb/pull/816

**Pull request merged**
