### PR TITLE
Fix for issue caused by JGitUtil removal

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by porcelli** [comment]
@manstis @Rikkola @wmedvede @desmax74 @jhrcek PRed the fix

**Comment by manstis** [comment]
Downstream failures are for the same reason (removal of ```JGitUtil```) and is being addressed by @desmax74 . Since this PR partially fixes the problem it's OK to merge. Thanks @porcelli

**Comment by psiroky** [comment]
@porcelli or @desmax74 are you guys working on the failure in kie-wb-common?

**Comment by manstis** [comment]
@psiroky We also need @porcelli or @desmax74 to submit a PR for ```droolsjbpm-build-bootstrap``` to update some dependency versions (that have been done in AF and are needed to _run_ the webapps in KieGroup).

**Pull request merged**
