### PR TITLE
[6.5.x] RHBPMS-4640: Unable to load repository in business central in administration

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/RHBPMS-4640

- cherry-pick: https://github.com/kiegroup/guvnor/pull/397

- Before:
before

- After:
after

### CODE REVIEW

**Comment by karreiro** [comment]
@Rikkola @porcelli Could you please take a look?

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by Rikkola** [comment]
@karreiro do you know who we can get to merge into 6.5.x? I also have 2 that should go into guvnor.

**Comment by karreiro** [comment]
@Rikkola I _think_ that @porcelli can help us with that :-)

**Pull request merged**
