### PR TITLE
GUVNOR-2933: Guvnor ALA integration

### PR DESCRIPTION
**Pull request by wmedvede**
- adds the hability of consuming the maven build messages produced by a pipeline

### CODE REVIEW

**Comment by wmedvede** [comment]
@porcelli The missing pointed out test is in place.

**Comment by wmedvede** [comment]
jenkins retest this.

**Comment by wmedvede** [comment]
jenkins retest this.

**Comment by wmedvede** [comment]
@porcelli Privior to invest more time getting this green...

Is there any chance to merge at least this PR? (to include the counter part in kie-wb-commons is not needed since nobody is using the maven build form the wb).
I've spent two days debuging the appformer showcase for some weird errors and this PR includes the fixes... . It'll also benefit the summit demo.

**Comment by porcelli** [comment]
@desmax74 is working on this.. and very close to get it done. thx @wmedvede for this.. but soon we'll have real maven :)

**Pull request closed without merging**
