### PR TITLE
Fix compilation error after remove of JGitUtil

### PR DESCRIPTION
**Pull request by manstis**
Fix compilation error after remove of JGitUtil by https://github.com/AppFormer/uberfire/pull/779

### CODE REVIEW

**Comment by manstis** [comment]
@wmedvede I ran the test locally but it took forever (never.. I got bored waiting) completed. 

Let's see what Jenkins makes of it.

**Comment by manstis** [comment]
@mbiarnes @Rikkola FYI

**Comment by manstis** [comment]
@wmedvede @porcelli It looks like changing to the "new" Command-based API leads to the test to fail.

I'll leave this with you two to resolve.

**Comment by wmedvede** [comment]
@manstis I had even no idea that this change will be produced. 
@porcelli Would you mind take a look please? This change is only for 8.0.0 or also for the 7.2.0?

**Pull request closed without merging**
