### PR TITLE
GUVNOR-2922 : [Test Scenario] Reporting panel is not shown

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-2922

- https://github.com/kiegroup/drools-wb/pull/423
- https://github.com/kiegroup/guvnor/pull/423

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis @jomarko Anyone interested, please take a look at this and the drools-wb PR.

**Comment by jomarko** [comment]
@Rikkola I am looking, thanks.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
Hi @Rikkola. I had look on both PRs. They seems fine to me. Also compiled locally and the Reporting panel works again. Thanks.

**Pull request merged**
