### PR TITLE
AF-593+: Move Guvnor modules to uberfire and kie-wb-common.

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
These PRs move Guvnor ALA to kie-wb-common, and all other Guvnor modules to uberfire.

These PRs intentionally do **not** rename packages from `org.guvnor.*` to more easily allow people currently working on Guvnor to rebase from this change. This should be done at a later date when we are ready to rename everything in uberfire to `org.appformer.*`

//cc @Rikkola @porcelli @manstis

**Comment by mbarkley** [comment]
@psiroky @mbiarnes So I suspect this PR will not go green because I have removed guvnor from the repository list in the related PR to droolsjbpm-build-bootstrap?

**Comment by manstis** [comment]
Approving since this is a copy and paste of existing guvnor code and this re-organization task should not be the subject of a thorough code review :-)

**Comment by Rikkola** [comment]
Thanks for pinging me. I like the idea of just moving the code at this point. Makes it easy for me to rebase locally.

**Comment by mbarkley** [comment]
So as far as I can tell, these PRs are ready to merge (I don't think this build will go green ever).

This branch is rebased on top of the most recent guvnor commits that have been copied to uberfire/kie-wb-common. If other open PRs are merged first I will need to update my uberfire/kie-wb-common PRs.

I see there are other guvnor PRs open that don't look ready to merge. "Rebasing" them will involve finding the moved modules in uberfire and kie-wb-common, and copying the changed files respectively. @manstis how do you want to handle this? Merge this first and make others update their PRs, or wait and merge the other open PRs first?

**Comment by manstis** [comment]
@mbarkley Hi.. the remaining PRs are all large, extensive changes to guvnor (that span multiple repositories). IMO in an ideal world those should all be merged and closed before this PR as merge of this PR will leave those with pending (and AFAIK incomplete PRs) in a rather horrible place. 

That said, IDK how/when the authors of the pending PRs expect to have them ready for merge. So, I'd propose you email those concerned - @Rikkola , @desmax74 and @ederign - to see how _they_ want these four monolithic changes handled across the different repositories.

Personally, I'm not affected, so could easily say "yeah go for it" but I know it's likely to upset those with other large x-repository PRs pending.. hence (politically) defer the decisions to those affected.

**Comment by mbarkley** [comment]
@manstis Fair enough. I will work something out with them.

**Comment by Rikkola** [comment]
@manstis @mbarkley Mine should be quite easy to apply after this (this should just move modules from A to B, I can use a diff tool to apply my changes on top of it). 

But if I get mine in before @mbarkley he probably has to start from 0.

**Comment by manstis** [comment]
@Rikkola @ederign @desmax74 Please approve this PR if you accept this one "goes first".. and your individual PRs will consequentially need rebasing/updating etc... when all approvals "are in" I will merge this @mbarkley

**Pull request merged**
