### PR TITLE
GUVNOR-2976: Guided Decision Table Graph: Save operation saves changes just to selected graph

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2976

This PR reinstates https://github.com/kiegroup/guvnor/commit/8e3676faa6e3790caaa7bf872f8c40db0a0c180f
which was inadvertently removed by https://github.com/kiegroup/guvnor/commit/f2cce32a65946a203b385667a64aeed51ee9d1b0

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:-

https://github.com/kiegroup/guvnor/pull/436
https://github.com/kiegroup/kie-wb-common/pull/775
https://github.com/kiegroup/drools-wb/pull/447

**Comment by manstis** [comment]
@karreiro @Rikkola @jomarko Care to review?

**Comment by manstis** [comment]
@etirelli Another candidate (and the other 2 related PRs) for backport to 7.0.... please confirm.

**Comment by etirelli** [comment]
@manstis +1, please apply the fixes to 7.0.0.CR2

**Pull request merged**
