### PR TITLE
GUVNOR-3128: Store Guvnor ALA state using VFS (#482)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 8fc79508f38d0eeaee737035fa6e09a2088cb0b2)

### CODE REVIEW

**Comment by wmedvede** [comment]
@porcelli This is the peer PR for the already merged into 7.2.x branch: 
    https://github.com/kiegroup/guvnor/pull/482

Would you mind review?
Thanks

depends on:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/498

**Comment by porcelli** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
This is the build error right now
duplicate declaration of version (?) @ org.kie:kie-spring:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-spring/pom.xml, line 283, column 17
18:14:55 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 25, column 17
18:14:55 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-

parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml, line 98, column 17
18:14:55 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-client:jar is missing. @ org.kie.server:kie-server-integ-tests-controller:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml, line 103, column 17
18:14:55 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-integ-tests-controller:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml, line 108, column 17
18:14:55 
18:14:55 	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
18:14:55 	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
18:14:55 	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
18:14:55 	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
18:14:55 	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
18:14:55 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
18:14:55 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
18:14:55 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
18:14:55 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)

**Comment by wmedvede** [comment]
jenkins retest this

**Pull request merged**
