### PR TITLE
GUVNOR-3128: Store Guvnor ALA state using VFS

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
@porcelli 7.2.x counterpart for closed on master.
Any chance to get this merged?

**Comment by wmedvede** [comment]
@porcelli  PR updated according to the last requested modifications.

**Comment by wmedvede** [comment]
@porcelli  PR re-updated according to the last requested modifications.

**Comment by porcelli** [comment]
jenkins please test this

**Pull request merged**
