### PR TITLE
[6.5.x] GUVNOR-2971 : [GSS](6.4.x)Artifact repository upload functionality allows malicious code injection

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-2971

(cherry picked from commit 228a9969ea2f50d16a5c0541caa2c465d5f135a5)

### CODE REVIEW

**Comment by Rikkola** [comment]
@karreiro Hi, same for 6.5.x

**Comment by manstis** [comment]
@Rikkola The JIRA doesn't appear to have any ACKs.. can I merge this!?

**Comment by manstis** [comment]
@Rikkola OK, I see https://issues.jboss.org/browse/RHBPMS-4627 has the ACKs.. 

However could you please confirm this can be merged (I see 6.4.3.CR1 "closed" on 7th April)

**Comment by Rikkola** [comment]
@manstis Sure, I'll check.

**Pull request merged**
